[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

[[redirects]]
  from = "/api/tags"
  to = "/.netlify/functions/tags"
  status = 200

[[redirects]]
  from = "/api/users/*/follow"
  to = "/.netlify/functions/users-id-follow"
  status = 200

[[redirects]]
  from = "/api/users/*/followers"
  to = "/.netlify/functions/users-id-followers"
  status = 200

[[redirects]]
  from = "/api/users/*/following"
  to = "/.netlify/functions/users-id-following"
  status = 200

[[redirects]]
  from = "/api/activity/feed"
  to = "/.netlify/functions/activity-feed"
  status = 200

[[redirects]]
  from = "/api/activity-feed-public"
  to = "/.netlify/functions/activity-feed-public"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/stats"
  status = 200

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200

[[redirects]]
  from = "/api/events/*/register"
  to = "/.netlify/functions/events-id-register"
  status = 200

[[redirects]]
  from = "/api/events/*/comments"
  to = "/.netlify/functions/events-id-comments"
  status = 200

[[redirects]]
  from = "/api/events/*/tags"
  to = "/.netlify/functions/events-id-tags"
  status = 200

[[redirects]]
  from = "/api/events/*"
  to = "/.netlify/functions/events-id"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "staging"

[context.branch-deploy.environment]
  NODE_ENV = "development"